theme = "hyde"
baseURL = "https://deviationstation.netlify.com/"
relativeURLs = true
disqusShortname = "deviationstation"
GoogleAnalytics = "UA-148958941-1"
languageCode = "en-us"
title = "data %>% hack"

[Menus]
  main = [
      {Name = "About", URL = "/about/"},
      {Name = "Blog", URL = "/blog/"},
      {Name = "Github", URL = "https://github.com/chris-lundberg/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/chris-lundberg/"}
  ]

[params]
  description = "Data journalism. Monthly posts exploring open data."
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsTheme = "monokai"

[permalinks]
  post = "/blog/:slug/"