---
title: Welcome! (Yes, I know where you are)
author: Chris Lundberg
date: '2019-09-28'
slug: welcome-yes-i-know-where-you-are
categories: []
tags: 
  - google analytics
Categories:
  - R
Description: ''
Tags:
  - google analytics
menu: blog
---

It seems appropriate for my first post to be about all the creepy things I can find out about my readers using [Google Analytics](https://analytics.google.com), as it will give you a chance to quickly leave if you don't want me to know your deep, dark secrets. 

For those of you with no intention of using google analytics or interest in the code in this post, you may still find the following details interesting, as there seems to be a general misunderstanding, at least among members of Congress, about what information is collected from internet users and who can access it:

```{r pichai-video, eval=TRUE, echo=FALSE}
blogdown::shortcode("youtube", "Oqw81WF_eqw")
```
\newline

The short answer to Rep. Ted Poe's question is that yes, Google knows where you are, and they share this information with every website you visit that embeds a Google Analytics tracking ID like this:

```{js ga-example, eval=FALSE}
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-123456789-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```


